name: sathachlaixe
description: "Ung dung ho tro thi ly thuyet dao tao giay phep lai xe"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.0

  #navigation
  go_router: ^15.0.0

  #utils
  logging: ^1.3.0
  flutter_svg: ^2.0.17

  #state 
  bloc: ^9.0.0
  provider: ^6.1.4
  flutter_bloc: ^9.1.0

  # Database
  hive: ^2.2.3
  shared_preferences: 2.5.3

  #DI
  get_it: ^8.0.3
  hive_flutter: ^1.1.0

  #gauges chart
  syncfusion_flutter_gauges: ^29.2.4
  intl: ^0.20.2

  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15


flutter:
  uses-material-design: true

  assets:
    - assets/drawables/