name: sathachlaixe
description: "Ung dung ho tro thi ly thuyet dao tao giay phep lai xe"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  #navigation
  go_router: ^16.2.1

  #utils
  logging: ^1.3.0
  flutter_svg: ^2.2.1

  #state 
  bloc: ^9.0.0
  provider: ^6.1.5
  flutter_bloc: ^9.1.1

  # Database
  hive: ^2.2.3
  shared_preferences: 2.5.3

  #DI
  get_it: ^8.2.0
  hive_flutter: ^1.1.0

  intl: ^0.20.2
  
  json_annotation: ^4.9.0
  
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

dependency_overrides:
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/drawables/
    - assets/bank/
    - assets/questions/