name: sathach
description: "Sat hach ly thuyet cap giay phep lai xe tai Vietnam"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.0.0
  logging: ^1.3.0
  shared_preferences: 2.5.3
  flutter_svg: ^2.0.17
  provider: ^6.1.4

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/questions/
    - assets/signs/
    - assets/banks/
    - assets/icons/
